### PR TITLE
Fixes to make it Xcode 6.3 compatible

### PR DESCRIPTION
**Pull request by markusl**

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
Why Byte -> Uint8 ?

**Comment by markusl** [comment]
@krzyzanowskim that is what Swift's migration wizard proposes (Edit -> Convert -> To Swift 1.2), the Byte version does not even compile with latest XCode.

**Comment by krzyzanowskim** [comment]
I have to take a deeper look at all other changes I thing, and can't merge it to master until Swift 1.2 become final.

**Comment by markusl** [comment]
Maybe you could merge it to a separate branch so that those users who need it, could easily take it into use?

**Comment by krzyzanowskim** [comment]
I'll change Byte -> Uint8 in master, then merge the rest to new branch

**Comment by krzyzanowskim** [comment]
I merged it manually, with minor change to branch swift12. Thank you @markusl

**Comment by krzyzanowskim** [comment]
Nah, I did it wrong. Now it's totaly broken. Can you merge you changes to branch "switch12" ?

**Pull request closed without merging**
