### PR TITLE
Solved bitmap error.

### PR DESCRIPTION
**Pull request by uny**
I recreated the project file with Xcode 8 beta 5, which solved the issue https://github.com/krzyzanowskim/CryptoSwift/pull/282 https://github.com/krzyzanowskim/CryptoSwift/issues/240#issuecomment-233434171.

There are differences of optimization level and they might cause the error.
If you don't care about the differences, the issue will be solved by merging this PR.

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
Oh Christ, are you able to separate if that's the optimization level that cause the problem ?

**Comment by krzyzanowskim** [comment]
@uny I wont merge this PR (breaks SPM, change target names), although it's great insight to Xcode 8 issues. Wonder if we can separate what exactly cause the problem to Xcode 8

**Comment by uny** [comment]
Sure, I did.
Link-time optiomazation seems to be the cause.

**Comment by krzyzanowskim** [comment]
From what I found it's not the parameter, I mean by that that maybe it fixes something by accident but in general it's not the ultimate workaround. Still waiting for next betas.

**Pull request closed without merging**
