### PR TITLE
Fixed Bug

### PR DESCRIPTION
**Pull request by McClementine**
Added 'import Foundation' to prevent build fail when running 'swift build'

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
Foundation is not used in this file, at all.
It must be something else.

**Comment by McClementine** [comment]
@krzyzanowskim NSData fails with "unresolved identifier 'NSData' ", which is fixed by importing foundation when using the 'open-source' version of swift. (I'm on Linux)

**Comment by krzyzanowskim** [comment]
but.... there is not NSData in this file

**Comment by McClementine** [comment]
@krzyzanowskim This is what my output is telling me

**Comment by McClementine** [comment]
@krzyzanowskim wrong file, will close and add new

**Pull request closed without merging**
