### PR TITLE
Added option to seed the CRC

### PR DESCRIPTION
**Pull request by richlowenberg**
At our organization seeding the CRC is necessary - thought this might be helpful for others too. Thanks for a great library!

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
?

**Comment by richlowenberg** [comment]
Sorry! Closed as I am adding the functionality to the extensions as well.

**Comment by krzyzanowskim** [comment]
ok, please create PR for `develop` branch

**Comment by richlowenberg** [comment]
Sure, will do.

**Pull request closed without merging**
