### PR TITLE
Update for Xcode 8 beta 6

### PR DESCRIPTION
**Pull request by uny**
Main change is https://github.com/krzyzanowskim/CryptoSwift/pull/305/commits/b6ffd740df25a1ed47f5b1a2735eb401a720fd90.
https://github.com/krzyzanowskim/CryptoSwift/commit/3539d28c3f689bb3941ec81ef2357977299b93f8 is for https://github.com/krzyzanowskim/CryptoSwift/pull/302

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
I believe most of it is already on swift3-snapshot branch, isnt it?

**Comment by uny** [comment]
Yes, you are right. Sorry.

**Comment by mxl** [comment]
@krzyzanowskim What's the difference between swift3 and swift3-snapshots branches? I think that everyone tries first swift3 branch and it's not compatible with Xcode 8 beta 6.

**Comment by krzyzanowskim** [comment]
snapshot is for swift3 snapshots and udually is ahead of swift3 branch

**Comment by mxl** [comment]
Thanks, I see. May be it's better to keep swift3 branch in sync with Xcode beta releases, because it's misleading now?

**Comment by krzyzanowskim** [comment]
swift3 is, It just happened apple released new xcode beta in the middle of my vacation. Ill revew changes and merge snapshot to swift3 after i back home

**Comment by mxl** [comment]
Ok, sorry then for bothering.

**Comment by krzyzanowskim** [comment]
Merged changes from swift3-snapshot brach.

**Pull request closed without merging**
