### PR TITLE
[*] - Sharing the scheme so the module can be compiled by command line t...

### PR DESCRIPTION
**Pull request by Vaseltior**
Making the scheme shared so that it can be used to compile with command line tools and also can be used with Carthage : https://github.com/Carthage/Carthage

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
that's great. Would you mind populate this change to branch swift12 as well ?

**Comment by Vaseltior** [comment]
I can it's just one checkbox to check. What is the purpose of the swift12
branch?

2015-03-11 10:46 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:

> that's great. Would you mind populate this change to branch swift12 as
> well ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krzyzanowskim/CryptoSwift/pull/37#issuecomment-78232498>
> .
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47

**Comment by krzyzanowskim** [comment]
swift12 is for Swift 1.2 (Xcode 6.3 beta). And current development branch to me.

**Comment by krzyzanowskim** [comment]
ok, I'll do it by hand

**Comment by Vaseltior** [comment]
Do you have any idea why I get this message, when trying to compile your
framework?
(if I build in xcode there is no issue by the way)

=== BUILD TARGET CryptoSwift OF PROJECT CryptoSwift WITH CONFIGURATION
Release ===


Check dependencies

Code Sign error: No code signing identities found: No valid signing
identities (i.e. certificate and private key pair) matching the team ID
“(null)” were found.

CodeSign error: code signing is required for product type 'Framework' in
SDK 'iOS 8.1'

2015-03-11 11:47 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:

> ok, I'll do it by hand
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krzyzanowskim/CryptoSwift/pull/37#issuecomment-78241114>
> .
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47

**Comment by krzyzanowskim** [comment]
this https://github.com/Quick/Quick/issues/79 may be related

**Comment by Vaseltior** [comment]
It is absolutely related!!! Thanks for finding that. Indeed, I created fake
test framework in order to get the default values. Both the debug and
release code sign identities are set to iPhone Developer. So I modified the
fork version of your framework, setting both identities to iPhone developer
and it worked like a charm.

Again, thanks for taking the time to check this.

2015-03-11 12:09 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:

> this Quick/Quick#79 <https://github.com/Quick/Quick/issues/79> may be
> related
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krzyzanowskim/CryptoSwift/pull/37#issuecomment-78243979>
> .
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47

**Comment by krzyzanowskim** [comment]
ok, so there should be one more change right ? I'm not on my machine so you can pull request and I'll merge it later.

**Comment by Vaseltior** [comment]
Ok

2015-03-11 13:46 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:

> ok, so there should be one more change right ? I'm not on my machine so
> you can pull request and I'll merge it later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krzyzanowskim/CryptoSwift/pull/37#issuecomment-78255982>
> .
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47

**Comment by krzyzanowskim** [comment]
Actually.... what is wrong with that: http://cl.ly/image/1y0c321H2010 Developer for debug, Distribution for release seems ok?

**Comment by Vaseltior** [comment]
This is ok for an Application, not in the case of a Framework I'd say.

2015-03-11 15:01 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:

> Actually.... what is wrong with that: http://cl.ly/image/1y0c321H2010
> Developer for debug, Distribution for release seems ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krzyzanowskim/CryptoSwift/pull/37#issuecomment-78267963>
> .
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47

**Comment by krzyzanowskim** [comment]
I can't explain that, and I wish I could explain that. Won't this change affect release builds ?

**Comment by Vaseltior** [comment]
In the final application, the bundle will be signed with production
certificates, so it will be ok.
If I want to distribute the framework, I can sign it with the production
certificate, and it works fine.
It's just that when I'm trying to compile it via Carthage it doesn't work,
telling me it can't be code signed.
I have no real explanation on this for now. I'm interested in knowing why
:-0

2015-03-13 0:14 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:

> I can't explain that, and I wish I could explain that. Won't this change
> affect release builds ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krzyzanowskim/CryptoSwift/pull/37#issuecomment-78683868>
> .
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47

**Comment by krzyzanowskim** [comment]
this one is merged to maste branch, but will disappear if will not be applied to develop branch

**Comment by coolgeng** [comment]
I get the similar issue. 

carthage version 0.7.4

log:

*** Building scheme "CryptoSwift" in CryptoSwift.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Pull request merged**
