### PR TITLE
[HMAC] Support SHA384 and SHA512

### PR DESCRIPTION
**Pull request by kylef**

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
Can you please prepare patch to develop branch ? I'll have to move it there manually.

**Comment by krzyzanowskim** [comment]
I'll cherry-pick this one.

**Comment by kylef** [comment]
Thanks :octocat:. Do you know when you plan to make a new version including these?

**Comment by krzyzanowskim** [comment]
I home Xcode 6.3 with Swift 1.2 will be released soon, and then new version from develop branch will be released as well.

**Pull request merged**
