### PR TITLE
Simple ASN1 Encoder and Decoder & DERCodable Protocol

### PR DESCRIPTION
**Pull request by btoms20**
Working towards #892

Checklist:
- [x] Correct file headers (see CONTRIBUTING.md).
- [x] Formatted with [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).
- [x] Tests added. (ASN1 specific tests added)

Changes proposed in this pull request:
- This PR implements a simple ASN1 Encoder and Decoder. Abstract Syntax Notation (ASN) is often used along side Distinguished Encoding Rules (DER) for [structuring cryptographic data](https://datatracker.ietf.org/doc/html/rfc2313#section-7) before, and after, processing it (processing includes importing, exporting, signatures & verification, encryption & decryption, etc). 
- This PR also introduces a `DERDecodable`, `DEREncodable` and `DERCodable` Protocol set that cryptographic keys, such as `RSA`, can conform to in order to support Importing and Exporting keys that are structured as an ASN1 DER representation.
- Apple's `Security` framework exports ASN1 DER representations when using the `SecKeyCopyExternalRepresentation` function. This PR would allow for exchanging / sharing RSA keys between CryptoSwift and Apple's `Security` framework. The `DEREncodable` Protocol exposes  two functions `externalRepresentation()` and `publicKeyExternalRepresentation()` that should result in the same external representation as Apple's `Security` `SecKeyCopyExternalRepresentation` function.
- This PR sets the groundwork for supporting the importing and exporting of PEM files.
- This PR would also enable `RSA` Signature and Verification functionality.

### CODE REVIEW

**Comment by btoms20** [comment]
Hey @krzyzanowskim! First off, awesome work with the CryptoSwift framework! 

I have the code for `RSA:DERCodable` conformance, and RSA Signatures and Signature Verification ready to submit once this PR is approved / merged.

I also have a preliminary implementation of RSA PEM support (including encrypted PEM, imports & exports) which would help close out issue  #892 and provide additional Key interoperability between frameworks (like Openssl, Apple's `Security`, etc...). Encrypted PEMs would also provide a secure method of saving keys between CryptoSwift sessions. 👍 

Let me know if anything in this PR needs to be changed in order to be approved.

Thanks!

**Comment by krzyzanowskim** [comment]
thank you! I'm on vacation, but will back to it after next week.

**Review by NathanFallet — CHANGES_REQUESTED** [review]
You need to add tests.

**Comment by btoms20** [comment]
Okay, will do! 👍

**Comment by btoms20** [comment]
Hey @NathanFallet, I added some ASN1 tests located at c242291adc75a44cfc06cafd290a9532c8df4246. 

I also added some additional documentation and notes regarding the current status of the ASN.1 implementation. It's an internal tool (not to be used by the end user) but only from within CryptoSwift for specific, tested, use cases, such as DER / PEM encoding and decoding.  

Let me know if you have any additional questions, concerns, changes, etc...

 Thanks

**Comment by NathanFallet** [comment]
If it is implemented in the library for internal use, why can't it be used publicly? Is it too hard to maintain?
I will take a look to your changes

**Comment by btoms20** [comment]
ASN1 is a giant standard, consisting of many sub standards and the implementation proposed in this PR is a small subset of the main standard useful for handling Cryptographic keys only. I think exposing a partial ASN1 implementation to the public facing API would be confusing and potentially unsafe.

**Pull request merged**
