### PR TITLE
Make unit tests run on iOS devices

### PR DESCRIPTION
**Pull request by pyrtsa**
This pull request adds a host application which is required for unit tests to run on device.

I call the host application CryptoSwiftDemo by convention; feel free to extend it into an actual demo that does something when launched as is. Currently, it just shows and empty UI (and exits when being run by the unit test project).

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
How should I run tests to make it work ?

```
2015-06-21 20:37:18.477 CryptoSwiftDemo[4648:1142291] Error loading /private/var/mobile/Containers/Data/Application/77A47B8A-06DA-4AB3-B5C2-A71AEADB1FBC/tmp/CryptoSwiftTests.xctest/CryptoSwiftTests:  dlopen(/private/var/mobile/Containers/Data/Application/77A47B8A-06DA-4AB3-B5C2-A71AEADB1FBC/tmp/CryptoSwiftTests.xctest/CryptoSwiftTests, 262): no suitable image found.  Did find:
	/private/var/mobile/Containers/Data/Application/77A47B8A-06DA-4AB3-B5C2-A71AEADB1FBC/tmp/CryptoSwiftTests.xctest/CryptoSwiftTests: code signature invalid for '/private/var/mobile/Containers/Data/Application/77A47B8A-06DA-4AB3-B5C2-A71AEADB1FBC/tmp/CryptoSwiftTests.xctest/CryptoSwiftTests'
DevToolsBundleInjection: Error loading bundle '/private/var/mobile/Containers/Data/Application/77A47B8A-06DA-4AB3-B5C2-A71AEADB1FBC/tmp/CryptoSwiftTests.xctest'

```

**Comment by pyrtsa** [comment]
Are you sure all targets are signed with the same provisioning profile?

I previously had problems with automatic provisioning identities when I had multiple developer accounts bound to the same Apple ID. Nowadays I use a different Apple ID for every team I work with. If that could be your problem, you could still try first changing the signing identity into whatever you use locally for every target, and then rebuild.

Obviosly, we should stick to "automatic" in an open-source project, so a private identity won't help others much, until Xcode 7 of course relaxes code signing altogether.

**Comment by j1881** [comment]
The "“Remove code signing oddities"-commit would fix Carthage issues I have been having.

**Comment by krzyzanowskim** [comment]
I'd like to see this PR against "develop" branch.

**Comment by pyrtsa** [comment]
I'm sorry but I don't really have the time to invest into this project right now. Please feel free to do whatever you like with this pull request. I'm happy if it helped anybody.

**Comment by catalandres** [comment]
Is there anything I can do to help you close this one?

**Comment by krzyzanowskim** [comment]
@catalandres you can try check it and verify build process, update PR etc

**Pull request closed without merging**
