### PR TITLE
set BITCODE_GENERATION_MODE to "bitcode" for Debug build config

### PR DESCRIPTION
**Pull request by emaloney**
having BITCODE_GENERATION_MODE set to "marker" as it currently is
on master makes it impossible to run Debug builds on an Apple TV
device; "bitcode" is required in order to build a framework that
works on device.

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
it shouldn't be any different than iOS

**Comment by emaloney** [comment]
All I know is if `BITCODE_GENERATION_MODE` is set to `marker`, I can't compile & run a tvOS on an Apple TV device in a `DEBUG` build.

If I change `BITCODE_GENERATION_MODE ` to `bitcode`, then I am able to compile & run.

Are you able to compile & run a `DEBUG` build on an Apple TV *without* setting `BITCODE_GENERATION_MODE ` to `bitcode`?

**Comment by emaloney** [comment]
I am going to recreate this pull request, if needed, from the latest master branch. Closing this pr.

**Comment by krzyzanowskim** [comment]
👍

**Pull request closed without merging**
