### PR TITLE
Repair the string decrypt failure

### PR DESCRIPTION
**Pull request by myloveCc**

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
What is is about? I don't get it.

**Comment by myloveCc** [comment]
i just commit,you don’t get it?

**Comment by krzyzanowskim** [comment]
;-) I rather asking what is the purpose of this change.

**Comment by myloveCc** [comment]
when i get the encrypted string with key and iv,but i can’t decrypt it with the same key and iv.you can test your code when you use the encrypt and  decrypt func in  StringExtension.swift .  you will see  the failure.

**Comment by myloveCc** [comment]
Maybe this solution is not the best. If there is a better way, tell me, thanks.

**Comment by myloveCc** [comment]
let key:[UInt8] = "data^$%#!dfafdrf".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!.arrayOfBytes()
let iv = Cipher.randomIV(AES.blockSize)
let needEncryptString = "Have a nice day"
 /*
 encrypt
 */
let encryptedString =  needEncryptString.encrypt(Cipher.AES(key: key, iv: iv, blockMode: CipherBlockMode.CBC))
println("encrypt string :\(encryptedString)”)
/*
decrypt
*/
let decryptString = encryptedString!.decrypt(Cipher.AES(key: key, iv: iv, blockMode: CipherBlockMode.CBC))
println("decrypt string :\(decryptString)")

**Comment by krzyzanowskim** [comment]
the API is changed now. closing this one.
```swift
let base64String = try! "my secret string".encrypt(AES(key: "secret0key000000", iv: "0123456789012345")).toBase64()
let decrypted = try! encryptedBase64.decryptBase64ToString(AES(key: "secret0key000000", iv: "0123456789012345"))
```

**Pull request closed without merging**
