### PR TITLE
Updates for Xcode9 beta5

### PR DESCRIPTION
**Pull request by sebastianvarela**

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
I don't want to create conflict with the develop branch, can you use https://github.com/krzyzanowskim/CryptoSwift/pull/467 and add swift4 specific fix ?

**Comment by Yasumoto** [comment]
This was super helpful, but makes sense about basing off #467. @sebastianvarela if I can lend a hand to thank you please let me know!

**Comment by krzyzanowskim** [comment]
@sebastianvarela thanks. I'll take it over and update swift4 branch without merging this PR

**Comment by sebastianvarela** [comment]
Sorry, i was out. Thanks a lot.

**Pull request closed without merging**
