### PR TITLE
fix pkcs7padding error

### PR DESCRIPTION
**Pull request by rakeyang**
Fixes #

Checklist:
- [ ] Correct file headers (see CONTRIBUTING.md).
- [ ] Formatted with [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).
- [ ] Tests added.

Changes proposed in this pull request:
-

### CODE REVIEW

**Comment by NathanFallet** [comment]
Is it linked to #865?

**Comment by krzyzanowskim** [comment]
@rakeyang do you mind elaborate about this change? testcase that trigger the issue for you is every much welcome. What is `padding` is `1`?

**Review by krzyzanowskim — CHANGES_REQUESTED** [review]
do you mind elaborate about this change? testcase that trigger the issue for you is every much welcome. What is `padding` is `1`?

**Comment by rakeyang** [comment]
> do you mind elaborate about this change? testcase that trigger the issue for you is every much welcome. What is `padding` is `1`?

sorry i forget this pull request.

the detail information at: https://en.wikipedia.org/wiki/PKCS_7

**Comment by krzyzanowskim** [comment]
I don't think this is a change we should merge in. I'm happy to back to discussion if provided more information behind the reasoning of the change.

**Pull request closed without merging**
