### PR TITLE
Adds performance tests for SHA digests

### PR DESCRIPTION
**Pull request by valeriyvan**
Fixes #

Checklist:
- [ ] Correct file headers (see CONTRIBUTING.md).
- [ ] Formatted with [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).
- [x] Tests added.

Changes proposed in this pull request:
- Adds performance tests for SHA digests

### CODE REVIEW

**Comment by valeriyvan** [comment]
> Please run `swift test --generate-linuxmain`

Did you mean committing  XCTestManifests.swift files?

**Comment by krzyzanowskim** [comment]
yes, please

**Comment by valeriyvan** [comment]
> yes, please

done

**Comment by krzyzanowskim** [comment]
thank you!

**Pull request merged**
