### PR TITLE
Added Android support

### PR DESCRIPTION
**Pull request by flangel**
Improvements #
- Added **Android support**
- CryptoSwift now runs on Android making it an outstanding library for Cross Platform cryptographic programming
- Tutorials can be found here 
-- https://docs.scade.io/docs/cryptoapp
-- https://www.youtube.com/watch?v=GGkqO-0yQ9Y

Checklist:
- [ ] Pull request against a `develop` branch.
- [ ] Correct file headers (see CONTRIBUTING.md).
- [ ] Formatted with [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).
- [x ] Tests added
  - Ran test to make sure it works on Android

Changes proposed in this pull request:
- Add Android support

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
thanks. It doesn't add much except it updates the docs. What are the possibilities to build it for Android outside the scade.io ?

**Comment by flangel** [comment]
Hi Marcin,

sorry for the delayed response:

Because CryptoSwift has no futher dependencies, it can be compiled to Android out of the box without additional changes to the Github project, so I only added the Android tag.

The current state of Swift for Android compiler has a couple of issues (Performance issues, bugs) that hamper the use. Also, there is no 32 bit support and no stable Swift Foundation for Android framework. 

We fixed all these above issues so CryptoSwift can run smooth and stable. Apart from that, I don't see limitations to compiling it outside SCADE. 

Viva Swift!
Frank

**Comment by krzyzanowskim** [comment]
When you say "we fixed all these above issues" what does it mean exactly?

I'm thinking, maybe there should be an Android related section in README that explain how to use it.

**Comment by krzyzanowskim** [comment]
@flangel are u willing to add a paragraph about Android use to the README ?

**Pull request merged**
